# a new release is executed at each new tag
on:
  push:
    tags:
     - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./widget
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install    
      - name: Install Fomantic
        working-directory: ./widget/node_modules/fomantic-ui
        run: npx gulp install    
      - name: Build Fomantic
        working-directory: ./widget/node_modules/fomantic-ui
        run: npx gulp build    
          #      - name: Test
          #        run: npm test --passWithNoTests
          #        env:
          #          CI: true
      - name: Generate build
        run: npm run build
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: widget-build
          path: ./widget/build
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./widget
    needs: build
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: widget-build
      # Zip the build using external action
      - name: Zip build
        uses: thedoctor0/zip-release@master
        with:
          filename: majority-judgment.zip
          path: widget-build
      # Upload as an artifact of the current workflow
      - name: Upload build zip artifact
        uses: actions/upload-artifact@v1
        with:
          name: majority-judgment.zip
          path: majority-judgment.zip
      # Make official GitHub release which will trigger
      # sending the mail with link for access
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: majority-judgment.zip
          token: ${{ secrets.GITHUB_TOKEN }}
